import os
import logging
from telegram import Update
from telegram.ext import Application, CommandHandler, ContextTypes
import asyncio

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO
)
logger = logging.getLogger(__name__)

from services.api_client import api_client
from services.qr_display import generate_qr_image

ADMIN_BOT_TOKEN = os.getenv("ADMIN_BOT_TOKEN")
ALLOWED_BARISTAS_STR = os.getenv("ALLOWED_BARISTAS", "123456789")
ALLOWED_BARISTAS = [int(x.strip()) for x in ALLOWED_BARISTAS_STR.split(",")]

def is_allowed(user_id: int) -> bool:
    return user_id in ALLOWED_BARISTAS

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id

    if not is_allowed(user_id):
        await update.message.reply_text("❌ У вас нет доступа к этому боту.")
        return

    await update.message.reply_text(
        "☕ *GiftForge Admin Bot*\n\n"
        "Доступные команды:\n"
        "🎯 /generate — Создать QR код для подарка\n"
        "📊 /stats — Статистика\n"
        "💰 /budget — Бюджет\n"
        "❓ /help — Помощь",
        parse_mode="Markdown"
    )

async def generate_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id

    if not is_allowed(user_id):
        await update.message.reply_text("❌ Нет доступа.")
        return

    message = await update.message.reply_text("🎯 Генерация QR кода...")

    try:
        result = await api_client.generate_qr(user_id)

        qr_url = result["qr_url"]
        expires_at = result["expires_at"]
        ttl = result["ttl_seconds"]

        img_buffer, _ = generate_qr_image(qr_url)

        await message.delete()

        await update.message.reply_photo(
            photo=img_buffer,
            caption=f"🎁 *QR код для подарка*\n\n"
                    f"⏳ Действителен: *{ttl//60} минут*\n"
                    f"🕐 Истекает: `{expires_at[:19]}`\n\n"
                    f"Покажите этот QR клиенту.\n"
                    f"Один QR = один подарок.",
            parse_mode="Markdown"
        )

        logger.info(f"QR generated by barista {user_id}")

    except Exception as e:
        logger.error(f"Error generating QR: {e}")
        await message.edit_text(f"❌ Ошибка генерации: {e}")

async def stats_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id

    if not is_allowed(user_id):
        await update.message.reply_text("❌ Нет доступа.")
        return

    try:
        stats = await api_client.get_stats()

        total = stats.get("total_gifts", 0)
        by_rarity = stats.get("by_rarity", {})
        budget = stats.get("budget", {})

        rarity_emojis = {"common": "☕", "rare": "🌟", "epic": "🔥", "mythic": "💎"}

        rarity_text = ""
        for rarity, data in by_rarity.items():
            emoji = rarity_emojis.get(rarity, "🎁")
            rarity_text += f"{emoji} {rarity.capitalize()}: {data['count']} ({data['stars']} Stars)\n"

        if not rarity_text:
            rarity_text = "Пока нет подарков\n"

        await update.message.reply_text(
            f"📊 *Статистика CoffeeShop*\n\n"
            f"🎁 Всего подарков: *{total}*\n\n"
            f"*По редкостям:*\n"
            f"{rarity_text}\n"
            f"*Бюджет:*\n"
            f"💰 Доступно: *{budget.get('available', 0):.0f}* Stars\n"
            f"📉 Потрачено: {budget.get('spent', 0):.0f} Stars",
            parse_mode="Markdown"
        )

    except Exception as e:
        logger.error(f"Error getting stats: {e}")
        await update.message.reply_text(f"❌ Ошибка: {e}")

async def budget_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_user.id

    if not is_allowed(user_id):
        await update.message.reply_text("❌ Нет доступа.")
        return

    try:
        budget = await api_client.get_budget()

        await update.message.reply_text(
            f"💰 *Бюджет CoffeeShop*\n\n"
            f"📥 Пополнено: *{budget['total_deposited']:.0f}* Stars\n"
            f"📉 Потрачено: *{budget['spent']:.0f}* Stars\n"
            f"✅ Доступно: *{budget['available']:.0f}* Stars",
            parse_mode="Markdown"
        )

    except Exception as e:
        logger.error(f"Error getting budget: {e}")
        await update.message.reply_text(f"❌ Ошибка: {e}")

async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "📖 *Помощь для бариста*\n\n"
        "1️⃣ Используйте /generate для создания QR\n"
        "2️⃣ Покажите QR клиенту (QR живёт 5 минут)\n"
        "3️⃣ Клиент сканирует QR через Client Bot\n"
        "4️⃣ Подарок отправляется автоматически\n\n"
        "⚠️ Один QR = один подарок.",
        parse_mode="Markdown"
    )

def main():
    if not ADMIN_BOT_TOKEN:
        logger.error("ADMIN_BOT_TOKEN not set!")
        return

    application = Application.builder().token(ADMIN_BOT_TOKEN).build()

    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("generate", generate_command))
    application.add_handler(CommandHandler("stats", stats_command))
    application.add_handler(CommandHandler("budget", budget_command))
    application.add_handler(CommandHandler("help", help_command))

    logger.info("🤖 Admin Bot запущен")
    application.run_polling()

if __name__ == "__main__":
    main()
